# .streamlit/secrets.toml

[snowflake]
user = "mmosey4"
password = ",ki8*IK<"
account = "rdb88181.us-east-1.aws"
warehouse = "klaus"
database = "ZENAS_ATHLEISURE_DB"
schema = "PRODUCTS"
role = "accountadmin"
